name: yolo_ultra
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - ca-certificates
  - certifi
  - openssl
  - pytorch=2.1
  - pytorch-cuda=12.1
  - torchaudio
  - torchvision
  - prettytable
  - pip
  - pip:
      - -e ./ultralytics-main
      - onnx==1.20.1
      - onnxruntime==1.23.2
      - py-cpuinfo==9.0.0
